dist: xenial
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- '3.9'
services:
- docker
jobs:
  include:
  - language: python
    python: '3.9'
    after_success:
    - sonar-scanner
install:
- pip install virtualenv --upgrade
- make install
- make test-install
script:
- make test
- if [[ "$TRAVIS_BRANCH" == "main"  ||  "$TRAVIS_BRANCH" == "travis" ]] && [ "$TRAVIS_PULL_REQUEST"
  == "false" ]; then echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}"
  --password-stdin; fi
- make cover
deploy:
- provider: script
  script: make docker-build && make docker-push
  skip_cleanup: true
  on:
    tags: true
    python: '3.6'
- provider: pypi
  skip_cleanup: true
  user: __token__
  password: "$PYPI_TOKEN"
  on:
    tags: true
    python: '3.6'
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: FbHzWXjWnpy97v4bmm75T15D0zLBdunEQ3l+w7LqC6cR2nCYOLqcIs2VvwJXXpSbSu9CVzRdMQYfsS7AYi+Fakg93nQOLEtkrhkYiq3yRKXsFVICaJOWPUQbZOdouTKtYZF/0P6FzjdBxbZeD7UW12FKiQ+dL9ncBrgGJExrqFo=
addons:
  sonarcloud:
    organization: "twilio"
    token:
      secure: uDJi2+fRxHes2S8/ZeCnLgalst3g/7ejUjVeTI596c3TTxDm+KFh7Nap1srVXjy0MIBPaOLoV/EPrt271C77XdNWarnz6dkqM4axWs/14DT2iRSQJuh90tr0s7mox7SkDE+W+AnPfv+807ksz0174AA4EIy/ubi2KcyHhhpYd0I=
