dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
services:
- docker
install:
- pip install virtualenv --upgrade
- make install
- make test-install
script:
- make test
deploy:
- provider: script
  script: make docker-build && make docker-push
  skip_cleanup: true
  on:
    tags: true
    python: '3.6'
- provider: pypi
  skip_cleanup: true
  user: __token__
  password: "$PYPI_TOKEN"
  on:
    tags: true
    python: '3.6'
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: n7ZtDd7AvPsw7Wd6fOCCWYiakWpCnYs1QqXpiozF9Rh1Z90XcrQp72utPFyl81jJp7zlgYWXSfHqmnUpbOCWd04WTsC4dkAY6dd/ThARV4kRkxONX3nlbRESOeZIWNXNOeSR1pg6sd9H7xwIDGmmN2arnFRNiQAD0y5li0yxAfQ=
