name: Run Tests

on: [push, pull_request]  # Ejecuta tests en cada push o PR

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js (Si usas Node, cambia según tu lenguaje)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install  # O el comando para tu proyecto

      - name: Run Tests
        run: npm test  # O el comando de tus tests
